import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Right Hand Venture",
  description: "Generated by create next app",
  keywords: "Marketing,Trending",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
